---
sidebar: sidebar
permalink: ontap98fo_technical_resources.html
keywords:
summary: This section contains links to various technical resources relevant to ONTAP 9.8.
---

= Technical Resources
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-19 13:00:26.441627
//

This section covers the technical resources available that detail the features mentioned in this document.

== Technical Reports

* TR-4067: NetApp ONTAP NFS Best Practices and Implementation Guide
+
https://www.netapp.com/us/media/tr-4067.pdf[https://www.netapp.com/us/media/tr-4067.pdf^]

* TR-4375: MetroCluster FC for ONTAP 9.7
+
https://www.netapp.com/us/media/tr-4375.pdf[https://www.netapp.com/us/media/tr-4375.pdf^]

* TR-4569: Security Hardening Guide for ONTAP 9
+
https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf[https://www.netapp.com/pdf.html?item=/media/10674-tr4569pdf.pdf^]

* TR-4571: NetApp FlexGroup Volumes Best Practices
+
https://www.netapp.com/us/media/tr-4571.pdf[https://www.netapp.com/us/media/tr-4571.pdf^]

* TR-4597: VMware vSphere with ONTAP
+
https://www.netapp.com/us/media/tr-4597.pdf[https://www.netapp.com/us/media/tr-4597.pdf^]

* TR-4598: FabricPool Best Practices
+
https://www.netapp.com/us/media/tr-4598.pdf[https://www.netapp.com/us/media/tr-4598.pdf^]

* TR-4678: Data Protection and Backup - FlexGroup Volumes
+
https://www.netapp.com/us/media/tr-4678.pdf[https://www.netapp.com/us/media/tr-4678.pdf^]

* TR-4689: MetroCluster IP Solution Architecture and Design
+
https://www.netapp.com/us/media/tr-4689.pdf[https://www.netapp.com/us/media/tr-4689.pdf^]

* TR-4705: NetApp MetroCluster Solution Architecture and Design
+
https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf[https://www.netapp.com/pdf.html?item=/media/13480-tr4705pdf.pdf^]

* TR-4743: FlexCache in ONTAP
+
https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf[https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf^]

== Podcasts

* Tech ONTAP Podcast Episode 263: Virtualization in ONTAP – Fall 2020
+
https://soundcloud.com/techontap_podcast/episode-263-virtualization-in-ontap-fall-2020-update[https://soundcloud.com/techontap_podcast/episode-263-virtualization-in-ontap-fall-2020-update^]

* Tech ONTAP Podcast Episode 264: NetApp ONTAP SnapDiff
+
https://soundcloud.com/techontap_podcast/episode-264-netapp-ontap-snapdiff[https://soundcloud.com/techontap_podcast/episode-264-netapp-ontap-snapdiff^]

* Tech ONTAP Podcast Episode 265: NetApp SnapMirror Cloud featuring ProLion
+
https://soundcloud.com/techontap_podcast/episode-265-netapp-snapmirror-cloud-featuring-prolion[https://soundcloud.com/techontap_podcast/episode-265-netapp-snapmirror-cloud-featuring-prolion^]

* Tech ONTAP Podcast Episode 266: NetApp ONTAP System Manager 9.8
+
https://soundcloud.com/techontap_podcast/episode-266-netapp-system-manager-98[https://soundcloud.com/techontap_podcast/episode-266-netapp-system-manager-98^]

* Tech ONTAP Podcast Episode 267: SnapMirror Business Continuity
+
https://soundcloud.com/techontap_podcast/episode-267-snapmirror-business-continuity-sm-bc-for-ontap-98[https://soundcloud.com/techontap_podcast/episode-267-snapmirror-business-continuity-sm-bc-for-ontap-98^]
