---
sidebar: sidebar
permalink: ontap98fo_netapp_ontap.html
keywords: TR-4872, 4872, introduction, NAS, SAN, NFS, SMB, S3, HA
summary: This page presents an overview of the latest features in ONTAP 9.8 and links to more information.
---

= TR-4872: NetApp ONTAP 9.8 Feature Overview
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

//
// This file was created with NDAC Version 2.0 (August 17, 2020)
//
// 2020-11-19 13:00:26.006047
//
Justin Parisi, NetApp

NetApp ONTAP is the industry-leading flagship data-management software from NetApp that enables you to seamlessly manage and protect your data wherever it lives, whether on-premises, at the edge, or in the cloud.

NetApp ONTAP offers support for the following features, all on the same platform:

* NAS protocols (NFS and SMB)
* SAN protocols (iSCSI, FCP, and NVMe)
* S3 data access
* Data protection (NetApp Snapshot copy, NetApp SnapMirror, and SnapVault technologies)
* Storage efficiencies (deduplication, compaction, and compression)
* High Availability (HA) failovers (including fast failovers for Tier-1 SAN with the All-SAN Array)
* Support for all-flash, spinning drive, and hybrid disk configurations
* Security features (multifactor authentication, NetApp Volume Encryption, and Secure Purge)

This is not a comprehensive list; if we included every feature offered by ONTAP, this document would be hundreds of pages long.

For more detailed information about NetApp ONTAP, see the https://www.netapp.com/pdf.html?item=/media/7413-ds-3231.pdf[ONTAP 9 data management software data sheet^] and the https://docs.netapp.com/ontap-9/index.jsp[product documentation^].

Check out this link:https://tv.netapp.com/detail/video/6211778986001[video] from NetApp Insight 2020 for a broader tour of noteworthy advances in NetApp ONTAP.

link:ontap98fo_simplicity_enhancements.html[Next: Simplicity Enhancements]
